/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef MEDIASCANNER_AUTODEFS_H
#define MEDIASCANNER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_MEDIASCANNER_NAME "MediaScanner"
#define S3E_EXT_MEDIASCANNER_HASH 0x306339ef

#endif /* !MEDIASCANNER_AUTODEFS_H */
