/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "MediaScanner_autodefs.h"
#include "s3eEdk.h"
#include "MediaScanner.h"
//Declarations of Init and Term functions
extern s3eResult MediaScannerInit();
extern void MediaScannerTerminate();


#if defined I3D_OS_IPHONE || defined I3D_OS_OSX

static void Scan_wrap(const char* filepath, const char* mime_type)
{
    IwTrace(MEDIASCANNER_VERBOSE, ("calling MediaScanner func on main thread: Scan"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)Scan, 2, filepath, mime_type);
}

#define Scan Scan_wrap

#endif /* I3D_OS_IPHONE */

void MediaScannerRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[1];
    funcPtrs[0] = (void*)Scan;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[1] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("MediaScanner", funcPtrs, sizeof(funcPtrs), flags, MediaScannerInit, MediaScannerTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int MediaScannerStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&MediaScannerRegisterExt;
    return 0;
}

int g_MediaScannerVal = MediaScannerStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    MediaScannerRegisterExt();
}
#endif

#endif
